# Generated by Django 2.0.5 on 2018-09-18 08:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True)),
                ('client_type', models.CharField(choices=[('client', 'Client'), ('end_user', 'End User')], max_length=10)),
                ('client_code', models.CharField(max_length=15)),
                ('client_name', models.CharField(max_length=1000)),
                ('tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=15)),
                ('telephon', models.CharField(max_length=15)),
                ('mobileno', models.CharField(max_length=15)),
                ('fax_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=150)),
                ('office_address', models.TextField()),
                ('alternate_address', models.TextField()),
                ('client_status', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=25)),
                ('created_ip', models.GenericIPAddressField(default='192.168.2.14')),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=25)),
                ('modified_ip', models.GenericIPAddressField(default='192.168.2.14')),
            ],
            options={
                'db_table': '4a_client_enduser',
            },
        ),
        migrations.CreateModel(
            name='Project_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(choices=[('', 'Select'), ('Active', 'In-Progress'), ('InActive', 'Closed'), ('Cancel', 'Cancelled'), ('Hold', 'Hold'), ('As-build', 'As Build')], max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '4a_project_status',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True)),
                ('project_code', models.CharField(max_length=15)),
                ('project_name', models.CharField(max_length=1000)),
                ('project_startdate', models.DateField(blank=True)),
                ('project_enddate', models.DateField(blank=True)),
                ('project_year', models.CharField(max_length=10)),
                ('project_description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=25)),
                ('created_ip', models.GenericIPAddressField(default='192.168.2.14')),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=25)),
                ('modified_ip', models.GenericIPAddressField(default='192.168.2.14')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='tms.Client_name')),
                ('enduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enduser', to='tms.Client_name')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tms.ProjectDetails')),
                ('project_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Project_status')),
            ],
            options={
                'db_table': '4a_projects',
            },
        ),
        migrations.CreateModel(
            name='Projecttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('', 'Select'), ('Project', 'Project'), ('Tender', 'Tender'), ('R_D', 'R & D')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '4a_project_type',
            },
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Projecttype'),
        ),
    ]
