# Generated by Django 2.0.5 on 2018-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Project', 'Project'), ('Tender', 'Tender'), ('R_D', 'R & D')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='project_type',
            field=models.CharField(choices=[('Project', 'Project'), ('Tender', 'Tender'), ('R_D', 'R & D')], max_length=10),
        ),
    ]
