# Generated by Django 2.0.5 on 2018-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_auto_20180918_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_name',
            new_name='Client',
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_type',
            field=models.CharField(blank=True, choices=[('', '--Select a Type --'), ('Project', 'Project'), ('Tender', 'Tender'), ('R_D', 'R & D')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='project_type',
            field=models.CharField(choices=[('', '--Select a Type --'), ('Project', 'Project'), ('Tender', 'Tender'), ('R_D', 'R & D')], max_length=10),
        ),
    ]
