# Generated by Django 2.0.5 on 2018-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_master_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_department',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
