# Generated by Django 2.0.5 on 2018-09-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0005_auto_20180924_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_hr', models.IntegerField(blank=True, null=True)),
                ('databank', models.IntegerField(blank=True, null=True)),
                ('dept_startdate', models.DateField(blank=True, null=True)),
                ('dept_enddate', models.DateField(blank=True, null=True)),
                ('dept_description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_ip', models.GenericIPAddressField(default='192.168.2.14')),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50)),
                ('modified_ip', models.GenericIPAddressField(default='192.168.2.14')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='tms.master_department')),
                ('dept_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_head', to='tms.master_department')),
                ('dept_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_manager', to='tms.master_department')),
                ('dept_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tms.Project_status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='tms.ProjectDetails')),
                ('subproject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subproject', to='tms.ProjectDetails')),
            ],
            options={
                'db_table': '4a_department_wise',
            },
        ),
    ]
